// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Koneksi langsung (bukan lewat pooler) — dipakai CLI Prisma (migrate/studio),
    // aman untuk DDL & advisory lock. Runtime aplikasi pakai DATABASE_URL (pooled)
    // lewat adapter di src/lib/prisma.ts.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
